### ISSUE TITLE
How can I get the ending time of a show?

### ISSUE THREAD

**Issue by n00d1e5** [moogar0880/PyTrakt#114]
Firstly, thank you for the excellent API. 
I do not need to purchase the service nor change TV show tracking app.

I checked the code and all issues, there is nothing about this.

You provide the function airs_date for the starting time of a show.
But I did not find any function for the ending time or the length (xx minutes) of show.

My use case is getting the show name and time, then add them to my Google Calendar.
(Because I am now using iTV Shows for iOS, it does not provide calendar sync feature.)
For inserting an event to Google Calendar, it requests, at least, title, starting time and ending time.
Currently, I set one hours for all episodes...

Thanks in advance.

**Comment by moogar0880** [comment]
Hey, this is a good question, and is probably something we could reasonably add a helper function for. I think the simplest thing to do would be to create a timedelta for the runtime and then add that to the `first_aired_date` of the episode. So something like this:

```python
from datetime import timedelta
from trakt.tv import TVEpisode

# get the episode, however you would typically do this in your script
episode = TVEpisode('Game of Thrones', season=1, number=1)

# create a timedelta instance for the runtime of the episode
runtime = timedelta(minutes=episode.runtime)

# calculate the end time as the difference between the first_aired_date 
# and the runtime timedelta
end_time = episode.first_aired_date + runtime
```

**Comment by n00d1e5** [comment]
> Hey, this is a good question, and is probably something we could reasonably add a helper function for. I think the simplest thing to do would be to create a timedelta for the runtime and then add that to the `first_aired_date` of the episode. So something like this:
> 
> ```python
> from datetime import timedelta
> from trakt.tv import TVEpisode
> 
> # get the episode, however you would typically do this in your script
> episode = TVEpisode('Game of Thrones', season=1, number=1)
> 
> # create a timedelta instance for the runtime of the episode
> runtime = timedelta(minutes=episode.runtime)
> 
> # calculate the end time as the difference between the first_aired_date 
> # and the runtime timedelta
> end_time = episode.first_aired_date + runtime
> ```

Thanks for your reply.
Usually, the end time is exactly what you said.
But, sometimes, there are some special episodes like recent F.B.I and F.B.I Most Wanted. They just combine two episodes into a longer one.

I will use your proposed method.
However, if the endtime is one of the official methods, that would be much better.

Hope everything goes well and be safe. :)
