### ISSUE TITLE
Promote 3.0.0

### ISSUE THREAD

**Issue by glensc** [moogar0880/PyTrakt#140]
GitHub releases are weird, once you start using releases, the plain git tags do not get promoted as the latest release:

- https://github.com/moogar0880/PyTrakt/tags
- https://github.com/moogar0880/PyTrakt/releases
- https://github.com/moogar0880/PyTrakt/releases/latest -> redirects to 2.2.0, not 3.0.0

To fix this, hit edit on 3.0.0 release and hit save. optionally fill release notes as well:
- https://github.com/moogar0880/PyTrakt/releases/tag/3.0.0

cc @moogar0880

**Comment by moogar0880** [comment]
Thanks for pointing this out. I hadn't realized that the github release didn't point at the latest tag. Should be fixed now 👍

**Comment by glensc** [comment]
latest **release**, not **tag** :D
