### ISSUE TITLE
TVShow - Season problems with Shows with the same name

### ISSUE THREAD

**Issue by Fizard** [moogar0880/PyTrakt#154]
I'm having problem when calling an object SEASONS with shows with the same name (but different Year). Like Hunter X Hunter or The Flash.
For an example, Hunter X Hunter has 2 different shows. "hunter-x-hunter-2011" and "hunter-x-hunter". I can search and find the correct one with the `show=trakt.tv.search('Hunter x Hunter',year=2011)` after filtering the right one as we can see with the following debug:
`logging.info("show.title: %s. show.year: %s. show.ids: %s. URL: https://trakt.tv/%s",show.title,show.year,show.ids,show.ext)`
Result: "INFO:root:show.title: Hunter x Hunter. show.year: 2011.show.ids: {'ids': {'trakt': 64409, 'slug': 'hunter-x-hunter-2011', 'imdb': 'tt2098220', 'tmdb': 46298, 'tvdb': 252322}}. URL: https://trakt.tv/shows/hunter-x-hunter-2011"
But when I use the function to get the SEASONS:
`season = show.seasons[2]`
`logging.info("season: %s. Season.ext: %s",season,season.ext)`
It gets the wrong series, not the 2011 as we can see in the result of the EXT (it brings only hunter-x-hunter and not the hunter-x-hunter-2011 that the variable is using:
Result: "INFO:root:Resposta de season: <TVSeason>: Hunter x Hunter Season 2. Season.ext: shows/hunter-x-hunter/seasons/2"

Maybe there is a problem with the SEASON filter and tv shows with the same name? The same thing happened with The Flash (1990) (https://trakt.tv/shows/the-flash) and The Flash (2014) (https://trakt.tv/shows/the-flash-2014).

If I can help with something else, please let me know. I don't know too much of python but I can try to help.

**Comment by moogar0880** [comment]
Thanks for the report @Fizard, this was definitely a bug. Version 3.2.1 should be available on PyPi shortly with a fix.

**Comment by Fizard** [comment]
Hi @moogar0880. Thanks for the answer, but when I upgraded to version 3.2.1 and tried to do the 
show=trakt.tv.search('Hunter x Hunter',year=2011)
season = show.seasons[2]
logging.info("season: %s. Season.ext: %s",season,season.ext)
The answer was still this:
Season: <TVSeason>: Hunter x Hunter Season 2. Season.ext: shows/hunter-x-hunter/seasons/2

Am I missing something?
