### ISSUE TITLE
init function "CLIENT_SECRET"

### ISSUE THREAD

**Issue by ralexay** [moogar0880/PyTrakt#16]
in **def init(username, client_id=None, client_secret=None, store=False)**:

**line 61**: CLIENT_ID, client_secret = client_id, client_secret

you are saving client_secret to **client_secret** instead of **CLIENT_SECRET** so that  this call
oauth.fetch_token(token_url, client_secret=CLIENT_SECRET, code=response)
will fail

same as saving json file:

 data = {'CLIENT_ID': CLIENT_ID, 'CLIENT_SECRET': CLIENT_SECRET ....,

**Comment by moogar0880** [comment]
Ah, good catch. I'll get a fix up for that shortly
