### ISSUE TITLE
sync.rate(), sync.add_to_history() don't pass 'movies', 'shows', etc. keys

### ISSUE THREAD

**Issue by woggle** [moogar0880/PyTrakt#21]
The [v2 API](http://docs.trakt.apiary.io/#reference/sync/add-ratings/add-items-to-watched-history) says sync/ratings and sync/history are supposed to accept a 'movies', 'shows', etc. JSON key with a list of JSON objects, but the code in sync.py simply passes the media object as the top-level JSON entity.

This seemed to silently not add/rate anything when I tried it; as a workaround I wrote my own rate function over @trakt.core.post that did seem to work:
```
@trakt.core.post
def rate(movie, rating, rating_time):
    data = movie.ids
    data.update(rating=rating, rated_at=rating_time)
    yield 'sync/ratings', {'movies': [data]}
```
so I don't think I had an auth/etc. problem.

**Comment by moogar0880** [comment]
hey @woggle. Sorry about the delay (been away on vacation for the last week). I have a branch up that I'm pretty sure fixes this issue. Still need to test it out a bit more tomorrow, but hopefully I'll be able to get a fix out for this shortly after that.

Thanks for alerting me to the problem!
