### ISSUE TITLE
Error with Unicode/UTF-8 Titles

### ISSUE THREAD

**Issue by AndiH** [moogar0880/PyTrakt#27]
While retrieving the title of a TV show, I got the following error:
```bash
'ascii' codec can't encode character u'\u2026' in position 16: ordinal not in range(128)
```
As it turned out, the reason for the error was the title of »Impastor« 1x02, which has a beautiful one-letter ellipsis [unicode character](http://www.fileformat.info/info/unicode/char/2026/index.htm) included on trakt (»[On the Third Day…](http://trakt.tv/shows/impastor/seasons/1/episodes/2)«). Unfortunately, PyTrakt does not seem to handle it properly.

Here is a minimal example:
```python
from trakt import tv
print tv.TVEpisode("impastor", 1, 2)
```

For me, I fixed it in line [L677 of tv.py](https://github.com/moogar0880/PyTrakt/blob/master/trakt/tv.py#L677), where I replaced `self.title` with `self.title.encode('utf-8')`. It seems kind of hack-ish, hence I did not open a pull request. For my taste, you probably want to built in the UTF-8 conversion earlier in the API retrieval process, as, apparently, trakt seems to have UTF-8 characters now.

**Comment by moogar0880** [comment]
Thanks for reporting this issue. I'll have a fix up shortly!
