### ISSUE TITLE
cant init

### ISSUE THREAD

**Issue by ghost** [moogar0880/PyTrakt#34]
when i try to import i get this error
from trakt import init

Installation went fine

```
>>> from trakt import init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name init
```

**Comment by moogar0880** [comment]
well that's peculiar... what version of Python is this happening on?

**Comment by Gutz-Pilz** [comment]
Python 2.7.3

**Comment by moogar0880** [comment]
that's so odd, it's working just fine for me on Python 2.7... did you install via `pip` or the setup.py?

**Comment by mgaulton** [comment]
I ran into this but switching python vers made it work

**Comment by glensc** [comment]
this is typically due conflicting trakt module, uninstall both and re-install the correct one.

```
$ pip3 list|grep trakt
trakt              3.1.0
trakt.py           2.8.0

pip3 uninstall trakt trakt.py
```

example:
- https://github.com/Taxel/PlexTraktSync/issues/306#issuecomment-830217795

**Comment by glensc** [comment]
@moogar0880 can be closed now with the answer.
