### ISSUE TITLE
Headers Bug?

### ISSUE THREAD

**Issue by BrendanBall** [moogar0880/PyTrakt#48]
I've been looking at this library hoping to use it but have had no luck so far.
according to this http://docs.trakt.apiary.io/#reference/authentication-oauth/token/get-shows 
both the Authorization header and trakt-api-key (clientId) should be present to make a successful request. I have tested this using postman and the api works correctly, however PyTrakt does not add the headers right.

before I do a request with MyShowCalendar, I set the OAUTH token and client id
trakt.core.OAUTH_TOKEN = access_token
trakt.core.CLIENT_ID = client_id

When I do a request the Authorization header results as `Bearer None` and the trakt-api-key is added correctly to the header.

trakt.core.CLIENT_SECRET = client_secret
If I additionally set the client secret then the Authorization header is added correctly (no longer none), but the trakt-api-key does not even appear in the header. 

Note that the trakt api requires to ALWAYS have the client id in the header. See 
http://docs.trakt.apiary.io/#introduction/required-headers

The client secret is only necessary when getting or renewing tokens so I shouldn't need to set that when doing an api call like get calendar. However if I do happen to set it, it shouldn't prevent the client id from being added to the header. I've tried looking at some of the code, however it is quite confusing at some parts.

**Comment by moogar0880** [comment]
Yup, that's definitely a bug. I'd always been setting all 3 variables so I'd never come across this. I've got a fix in place though, should that up soon. Thanks for the bug report
