### ISSUE TITLE
Some errors in Python 3.5

### ISSUE THREAD

**Issue by danialbehzadi** [moogar0880/PyTrakt#50]
Hi. I just looked into this project and found some errors with python 3.5.1

    In [1]: import trakt
    
    In [2]: from trakt.users import User
    
    In [3]: me = User('danialbehzadi')
    
    In [4]: me.name
    Out[4]: 'Danial Behzadi'
    
    In [5]: me.show_collection
    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-5-d6ecab873884> in <module>()
    ----> 1 me.show_collection
    
    /usr/local/lib/python3.5/dist-packages/trakt/core.py in inner(*args, **kwargs)
        313             json_data = self._handle_request('get', url)
        314             try:
    --> 315                 return generator.send(json_data)
        316             except StopIteration:
        317                 return None
    
    /usr/local/lib/python3.5/dist-packages/trakt/users.py in show_collection(self)
        322             self._show_collection = []
        323             for movie in data:
    --> 324                 mov = movie.pop('movie')
        325                 extract_ids(mov)
        326                 movie['movie'] = mov
    
    KeyError: 'movie'
    
    In [6]: me.friends
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-7-aa98d74db51f> in <module>()
    ----> 1 me.friends
    
    /usr/local/lib/python3.5/dist-packages/trakt/core.py in inner(*args, **kwargs)
        313             json_data = self._handle_request('get', url)
        314             try:
    --> 315                 return generator.send(json_data)
        316             except StopIteration:
        317                 return None
    
    /usr/local/lib/python3.5/dist-packages/trakt/users.py in friends(self)
        229                 user_data = user.pop('user')
        230                 date = user.pop('friends_at')
    --> 231                 self._friends.append(User(followed_at=date, **user_data))
        232         yield self._friends
        233 
    
    AttributeError: 'NoneType' object has no attribute 'append'

**Comment by moogar0880** [comment]
Just pushed a handful of updates that fixed this for me on Python 3.5.1. Do a `pip install trakt==2.4.3` and trying again. Thanks for reporting the bug :smile:
