### ISSUE TITLE
Slugify bug?

### ISSUE THREAD

**Issue by permster** [moogar0880/PyTrakt#51]
There appears to be some differences in how your slugify function works in utils.py compared to the trakt slugs.  Are they supposed to match?  Without them matching the _get functions in movies.py and tv.py class inits are prone to error as these rely on the slug to pull the information.  Here's an example.

title:  Marvel's Agents of S.H.I.E.L.D.
pytrakt slug:  marvels-agents-of-shield
trakt slug:  marvel-s-agents-of-s-h-i-e-l-d

Also, I noticed that in movie.py your joining the year (if passed) to the slug but you don't have the same logic in tv.py.  Is there a reason to not include that?  TV Shows with the same title also use the year in the slug to differentiate the shows.

**Comment by moogar0880** [comment]
They definitely used to match, or at least I haven't hit a situation in which they didn't. That being said, it looks like trakt is completely removing punctuation instead of escaping those characters. I'll get a fix up for this soon, I'll try to see if I can dig up any documentation on their actual slug-ification process first though

**Comment by permster** [comment]
Might be easier than I thought.  Instead of this in the slugify function.
`value = re.sub('[^\w\s-]', '', value).strip().lower()`

You can just replace with a space since you replace spaces with hyphens in the next line of code.
`value = re.sub('[^\w\s-]', ' ', value).strip().lower()`

This handles the single quotes and the periods.  Not sure yet whether that handles all scenarios or not though.  The only other thing would be to do a join to add the year to the end of the slug in tv.py (optional if year specified).

**Comment by permster** [comment]
I haven't found an issue with the change I mentioned in the last post yet.  However, I did notice issues with accents in show titles like **Naruto Shippūden**.

The line `value = unicode(value)` in the slugify function is encoding ascii which bombs due to the accent.  This would need to be changed to something like `value = unicode(value, 'utf-8')` perhaps but I don't know if that will work for everything.

**Comment by moogar0880** [comment]
hm, well that's an interesting problem. finding the closest possible ascii character to unicode character isn't something I've dealt directly with before, but looking at some SO posts it looks pretty doable. I'll poke around with it and see if I can get a solution that works together
