### ISSUE TITLE
Person slugify and duplicate names

### ISSUE THREAD

**Issue by permster** [moogar0880/PyTrakt#60]
I don't believe the slugify function is capable of handling people with the same name.  Here is an example of trakt slugs from two different people with the same name.

michelle-williams
michelle-williams-37d501c9-25c1-4bb2-afbd-51bbe9d79d96

The only rub here is that I can't figure out how trakt handles this either.  It adds some sort of a guid to the end of the slug and I can't find any documentation on it.

**Comment by permster** [comment]
I posed the question out to the Trakt community on Google+ in case someone knows how that is generated.  It's possible there is nothing we can do to handle that in your slugify function.

**Comment by moogar0880** [comment]
any updates from the trakt google+? I'm assuming that there's no way to guess those uuid's programmatically though, which is unfortunate. I guess you could search for the person you're looking for, but even then I'm not entirely sure how you'd determine that you found the one you're looking for...

**Comment by permster** [comment]
No it doesn't look like it.  Search was also suggested on trakt google+ but like you said how would you determine the right one.  I think I'll go ahead and close this one out.
