### ISSUE TITLE
APPLICATION_ID is not exposed

### ISSUE THREAD

**Issue by RB14** [moogar0880/PyTrakt#70]
The APPLICATION_ID of the core module cannot be set by the user since it's not exposed in `__all__`.
This results in an error raised by trakt.init (when called **without** a PIN, but **with** a client_id and client_secret), saying that the user must set the APPLICATION_ID variable.

```
import trakt

trakt.APPLICATION_ID = 'my_application_id'  # this will not set the correct APPLICATION_ID variable
```

**Comment by moogar0880** [comment]
Yup, that certainly looks like a problem. should be simple enough, I'll get a fix out for it shortly!

**Comment by moogar0880** [comment]
Should be all set. if you continue having issues, feel free to reach out!
