### ISSUE TITLE
Init not working

### ISSUE THREAD

**Issue by silverWeaver** [moogar0880/PyTrakt#72]
Init() function seems it's not working. Either with PIN or OAUTH authentication the following happens:

init(username)

And then it asks for:
Please enter your client id: xxxxx
Please enter your client secret: yyyy
Please enter your application ID (None): (no idea what to put here but I think it doesn't matter)

And process ends. Nothing has happened and of course I'm not authenticated.

**Comment by silverWeaver** [comment]
I now figured out that application id is the client id. Now it asks for the PIN but the URL provided is not valid. It shows a 404 page.

https://trakt.tv/pin/xyz

Is this because trakt depricated PIN authorization? But even if I OAUTH the behaviour is exactly the same

**Comment by moogar0880** [comment]
Hmmm, I wasn't aware that trakt had deprecated PIN auth, that's unfortunate. 

That being said, the OAUTH workflow seems to be working fine for me. Are you sure that it's failing? As long as `AUTH_METHOD` is set to `OAUTH_AUTH`, a successful auth shouldn't yield any output, other than an OAUTH access token that `init` returns.

our of curiosity, what version of python are you running on?

**Comment by silverWeaver** [comment]
Hello. Thanks for the response.
I'm running Python 2.7.9
Even with OAUTH doen't seem that it works
My problem is during initial setup for authentication. 
Exact commands and output:

```
>>> import trakt
>>> print trakt.AUTH_METHOD
PIN
>>> trakt.AUTH_METHOD = trakt.OAUTH_AUTH
>>> print trakt.AUTH_METHOD
OAUTH
>>> init('xxxx')
If you do not have a client ID and secret. Please visit the following url to create them.
http://trakt.tv/oauth/applications
Please enter your client id: xxx (my client id)
Please enter your client secret: xxxx (my client secret)
Please enter your application ID (None): xxxx (my client id)
>>>
```

And it stops there. I don't see the following: 

```
Please go here and authorize, <authorization_url>
Paste the Code returned here:
```

as it is being described here: http://pytrakt.readthedocs.io/en/latest/getstarted.html#oauth-auth

**Comment by zodman** [comment]
try with:

import trakt
import trakt.core

trakt.core.AUTH_METHOD=trakt.core.OAUTH_AUTH
trakt.init()

**Comment by zodman** [comment]
check PR #74

**Comment by StoneMonarch** [comment]
@silverWeaver `application id` is not `client id`

when you got to your API settings on the trakt website, its the 5 didgit number that the url ends with

**Comment by moogar0880** [comment]
Closing this issue out due to it's age. Feel free to open a new issue if this is still a problem.
