### ISSUE TITLE
Stuck after init.

### ISSUE THREAD

**Issue by psyciknz** [moogar0880/PyTrakt#77]
I must be missing something.  Once I've done an init and received an oath code, how do I then use that for one of the other functions, say the User.watching.

There doesn't seem to be a way of transfering the token for use

**Comment by moogar0880** [comment]
You shouldn't have to do much of anything. Your tokens will be stored as globals and are inherently used when communicating to the API. So, once authenticated, calling `User.watching` should be able to automatically use your credentials.

Are you using the [OAuth Auth](http://pytrakt.readthedocs.io/en/latest/getstarted.html#oauth-auth) method? If not I'd advise trying that.

**Comment by glensc** [comment]
@moogar0880 perhaps close stale issue?
