### ISSUE TITLE
Problems with TVShow & Python 2.7.5

### ISSUE THREAD

**Issue by normsland** [moogar0880/PyTrakt#9]
I having problems even getting PyTrakt to return anything. Even simple code...
from trakt.tv import TVShow
it_crowd = TVShow('The IT Crowd')
tvpeople = it_crowd.people

Produces the following Traceback (most recent call last):
  File "test1.py", line 8, in <module>
    it_crowd = TVShow('The IT Crowd')
  File "/ffp/lib/python2.7/site-packages/trakt/tv.py", line 100, in __init__
    self._get()
  File "/ffp/lib/python2.7/site-packages/trakt/_core.py", line 87, in inner
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/ffp/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/ffp/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/ffp/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Thanks

**Comment by moogar0880** [comment]
Out of curiosity, what version of PyTrakt are you running? 
```python
import trakt
print trakt.__version__
```
I only ask because some of the line numbers in that stack trace look a little odd...

But regardless, my initial thought would be that you aren't setting `trakt.api_key`, or you're setting it to a Trakt APIv1 API key. If you haven't already done so, I'd try running `trakt.init` and running through the manual steps that it provides you for authorizing PyTrakt

```python
import trakt
from trakt.tv import TVShow
my_api_key = trakt.init('myusername')

it_crowd = TVShow('The IT Crowd')
tvpeople = it_crowd.people
```

The `trakt.init` function will put your API key in place when you run it, but you should only need to run that once. After that, it's up to you to decide how you want to hang on to that key, but going forward you'll just need to do 
```python
import trakt
from trakt.tv import TVShow

trakt.api_key = my_api_key
it_crowd = TVShow('The IT Crowd')
tvpeople = it_crowd.people
```

Interestingly enough, searching for The IT Crowd did yield an interesting bug where, apparently, Trakt no longer standardizes on the format that they use for `first_aired` dates which causes an IT Crowd search to fail, so I'll get a fix up for that later today. 

If the api key is not the issue, let me know and I can try to come up with other some other possibilities, but performing that same operation appears to be working with a valid API key set:

```python
In [1]: import trakt

In [2]: trakt.api_key = my_api_key

In [3]: from trakt.tv import TVShow

In [4]: it_crowd = TVShow('The IT Crowd')

In [5]: it_crowd.people
Out[5]: 
[<Person>: Richard Ayoade,
 <Person>: Katherine Parkinson,
 <Person>: Matt Berry,
 <Person>: Graham Linehan,
 <Person>: Chris O'Dowd,
 <Person>: Ash Atalla,
 <Person>: Richard Boden,
 <Person>: Jamie Glazebrook,
 <Person>: Derrin Schlesinger,
 <Person>: FremantleMedia]
```

**Comment by moogar0880** [comment]
Got the date formatting fix up, you should be able to update `trakt` and successfully pull down The IT Crowd with a valid API key in place.

Keep me posted!

**Comment by normsland** [comment]
Hi Jon 

Thanks for looking in to this. I am still having a problem I am using
python on a raspberry pi running raspbian (debian). 

Traceback (most recent call last):
 File "test2.py", line 10, in <module>
 it_crowd = TVShow('The IT Crowd')
 File "/usr/local/lib/python2.7/dist-packages/trakt/tv.py", line 100, in
__init__
 self._get()
 File "/usr/local/lib/python2.7/dist-packages/trakt/_core.py", line 89,
in inner
 json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
 File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
 return _default_decoder.decode(s)
 File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
 raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I have run init and received my api key back from trakt. Any ideas of
what I could be missing? Could be a missing dependency I am guessing.
He's the list of packages installed by pip.. 

pi@raspberrypi ~ $ sudo pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
RPi.GPIO==0.5.11
argparse==1.2.1
babelfish==0.5.1
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
guessit==0.7.1
numpy==1.6.2
oauthlib==0.7.2
psutil==2.0.0
pygame==1.9.1release
requests==2.4.3
requests-oauthlib==0.4.2
simplejson==3.4.0
stevedore==0.15
trakt==1.0.3
wsgiref==0.1.2

Any help would be gratefully received. 

Thanks 

Martin 

On 2015-02-28 20:21, Jon Nappi wrote: 

> Out of curiosity, what version of PyTrakt are you running? 
> 
> import trakt
> print trakt.__version__
> 
> I only ask because some of the line numbers in that stack trace look a little odd... 
> 
> But regardless, my initial thought would be that you aren't setting trakt.api_key, or you're setting it to a Trakt APIv1 API key. If you haven't already done so, I'd try running trakt.init and running through the manual steps that it provides you for authorizing PyTrakt 
> 
> import trakt
> from trakt.tv import TVShow
> my_api_key = trakt.init('myusername')
> 
> it_crowd = TVShow('The IT Crowd')
> tvpeople = it_crowd.people
> 
> The trakt.init function will put your API key in place when you run it, but you should only need to run that once. After that, it's up to you to decide how you want to hang on to that key, but going forward you'll just need to do 
> 
> import trakt
> from trakt.tv import TVShow
> 
> trakt.api_key = my_api_key
> it_crowd = TVShow('The IT Crowd')
> tvpeople = it_crowd.people
> 
> Interestingly enough, searching for The IT Crowd did yield an interesting bug where, apparently, Trakt no longer standardizes on the format that they use for first_aired dates which causes an IT Crowd search to fail, so I'll get a fix up for that later today. 
> 
> If the api key is not the issue, let me know and I can try to come up with other some other possibilities, but performing that same operation appears to be working with a valid API key set: 
> 
> In [1]: import trakt
> 
> In [2]: trakt.api_key = my_api_key
> 
> In [3]: from trakt.tv import TVShow
> 
> In [4]: it_crowd = TVShow('The IT Crowd')
> 
> In [5]: it_crowd.people
> Out[5]: 
> [<Person>: Richard Ayoade,
> <Person>: Katherine Parkinson,
> <Person>: Matt Berry,
> <Person>: Graham Linehan,
> <Person>: Chris O'Dowd,
> <Person>: Ash Atalla,
> <Person>: Richard Boden,
> <Person>: Jamie Glazebrook,
> <Person>: Derrin Schlesinger,
> <Person>: FremantleMedia]
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/moogar0880/PyTrakt/issues/9#issuecomment-76544032

**Comment by normsland** [comment]
I have tried this on 3 environments now (NAS box Linux, Pi Linux, Windows 7 laptop) unfortunately still now luck. I have copied and pasted your commands one by one but unfortunately it still hasn't worked for me. Tried both v1 and v2 api key too. Sorry.

**Comment by moogar0880** [comment]
Hm...I'm really not sure what the issue could be... Although, If you're interested in poking around a bit, I could put some debug logging in on the API response, so we can try to get a better idea of what trakt is getting and sending back to you? Now that I think about it, this is probably a worthwhile endeavor anyway.

If it turns out to now be a networking issue, you might be able to get what you want by searching for the show, like so: 

```python
import trakt
from trakt.tv import TVShow

trakt.api_key = my_api_key
results = TVShow.search('The IT Crowd')
it_crowd = None
for result in results:
    if result.title == 'The IT Crowd':
        it_crowd = result
        break
```
although search results return less data about the show, so you may not be able to get everything you're looking for this way

**Comment by normsland** [comment]
Cracked it! Went to http://trakt.tv/oauth/applications created my own API App. Downloaded the source from github direct. Then edited _core.py entered my own CLIENT_ID and CLIENT_SECRET. Then built it using setup.py Now I can get results eg.
>>> print tvpeople
[<Person>: Richard Ayoade, <Person>: Katherine Parkinson, <Person>: Matt Berry,
<Person>: Graham Linehan, <Person>: Chris O'Dowd, <Person>: Ash Atalla, <Person>
: Richard Boden, <Person>: Jamie Glazebrook, <Person>: Derrin Schlesinger, <Pers
on>: FremantleMedia]

So it looks as though when you perform the init functionality you need to enable people to add their own CLIENT_ID and CLIENT_SECRET as well as their Trakt username.

**Comment by moogar0880** [comment]
Damn, that sounds so horribly inconvenient... There has to be another way though...I can't imagine that authenticating through PyTrakt would need to be much different that authentication through, say, a mobile app... 

Let me do some digging and see if there's not another way to make this easier for developers to use. I'd really rather not have to make users have to log into trakt, create a new oauth application, and _then_ run `init` to get an api key, just to be able to use this library. Maybe there really is no other way, but I'll at least go poke around in their docs and support forums and see if I can't scrounge up any additional information. 

Thanks for the info though, it's much appreciated

**Comment by moogar0880** [comment]
Yeah, unfortunately, it looks like the official word from Trakt is:

> For personal scripts, you can create a new OAuth app, then grant access for your own user. Then send that OAuth key along with all the API calls.

So, I guess there's not much I can do to remedy this

I'll go ahead and update the docs, `init` and `_core.py` to reflect these changes
