### ISSUE TITLE
PIN Auth not working - Keeps prompting OAuth instead

### ISSUE THREAD

**Issue by caffeinatedMike** [moogar0880/PyTrakt#91]
```
import trakt

my_username = 'CaffeinatedMike'
my_app_id = 'REDACTED'
my_client_id = 'REDACTED'
my_client_secret = 'REDACTED'

trakt.core.AUTH_METHOD = trakt.core.PIN_AUTH
trakt.core.CLIENT_ID = my_client_id
trakt.core.CLIENT_SECRET = my_client_secret
trakt.core.APPLICATION_ID = my_app_id

#Below Pin was retrieved by visiting https://trakt.tv/pin/{my_app_id}
trakt.core.init('2F741FD7')
premieres = trakt.calendar.PremiereCalendar(days=1)
print(premieres)
```

This results in the following output in the console
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: C:\Users\Mike\Downloads\testingtrakt.py ==============
If you do not have a client ID and secret. Please visit the following url to create them.
http://trakt.tv/oauth/applications
Please enter your client id: 
```

Is there anyway to fix this so that PIN auth will work correctly?

**Comment by p0psicles** [comment]
Why would you even want to use it? Its stated to be depricated. And there are already better alternatives?

**Comment by caffeinatedMike** [comment]
Because I had way too many issues implementing OAuth for it.

**Comment by p0psicles** [comment]
Okay. So now your having issues with pin. If you get that to work, in two months pin could be deactivated, and you would need to sort out your oauth issues anyway? Better to invest your time into getting oath to work now.

**Comment by caffeinatedMike** [comment]
@p0psicles You're right. It's just I'm at a loss how to get OAuth working for my scenario. I'm attempting to create a component for [Home Assistant](https://www.home-assistant.io/) and have been trying to study some of their components that deal with OAuth ([Spotify](https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/media_player/spotify.py) & [Nest](https://github.com/home-assistant/home-assistant/tree/master/homeassistant/components/nest)) and have had a lot of trouble getting a grasp on the whole process. I know this is a lot to ask, but do you think you could possibly assist me in any way?

**Comment by p0psicles** [comment]
Sure. I can help a little. I added the oauth device auth for pytrakt. So i know a bit on how to implement that. Just two steps actually.

**Comment by caffeinatedMike** [comment]
Ok, in that case here goes nothing. Given the way Home Assistant's components are structured I need to be able to automatically redirect to the auth page, which I haven't been able to accomplish with this module. During Initialization of the environment I'm prompted to enter the auth code before Home Assistant can even start up. The flow needs to be:

1. Home assistant is "booted up" using command line command `py -m homeassistant --open-ui`
2. Then, if the platform (trakt) is found in the `configuration.yaml` file the component should show up under the Configuration section of the UI
3. If the user selects to enable the component *that's* when they should be shown the Auth page in order to Authorize the application and obtain the access token/code/etc.

Does that sound doable? Up until now I kept getting stuck at being prompted for the code prior to Home Assistant booting up, which won't work for most installations (since many users run the program on a Raspberry Pi).

Right now I've been messing around/tweaking the Spotify module (that also uses some sort of OAuth flow), but I think the trakt component needs to be a sensor opposed a media_player component.

**Comment by p0psicles** [comment]
Do you have another repo or fork where i can assist. I should be able to help a little coming days.

**Comment by caffeinatedMike** [comment]
@p0psicles I no longer have issues with the authentication part, since I found a [custom_component](https://github.com/custom-components/sensor.trakt) for [Home Assistant](https://www.home-assistant.io/) that's already been created that handles the auth correctly. 

I will be forking this repo in a sec though in order to attempt to fix the error highlighted in my other issue (#94) where another user concurred with me that there is an issue with `TVEpisode` objects returned from Calendars not having all relevant data (in the case of the linked issue, I couldn't get `first_aired_date`). They proposed a [temporary workaround](https://github.com/moogar0880/PyTrakt/issues/94#issuecomment-431182401), which will hopefully help us diagnose and correct the issue.

If you'd like to help with that feel free to contribute to my fork.
