### ISSUE TITLE
Automatic OAUTH possibility without console

### ISSUE THREAD

**Issue by Forcide** [moogar0880/PyTrakt#93]
I would like the ability to directly input the OAUTH pin in trakt.init()
For example, I got a OAUTH pin in advance and would like to input this via a website.
But that is not possible right now because you need to input the OAUTH pin via a console.

I tested just pasting the OAUTH pin I got in advance.

**Comment by moogar0880** [comment]
Hey @Forcide, if you already have a valid access token, you should be able to set `trait.core.OAUTH` to the value of that token and skip the call to `init`entirely.

If that doesn't work let me know and I can dig in a bit more.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Forcide** [comment]
Thank you for the response.

That is not exactly what I would like to achieve, I want to get a valid token. But I like to automate the procedure for this by adding to OAUTH pin you get from going and copying the PIN from the: "Please go here and authorize, https://api-v2launch.trakt...." page in advance without the need to copy this back in the console.

I get that you add some kind of redirect and username at the end of the URL, but in my case/experience this was not necessarily needed.

**Comment by moogar0880** [comment]
Hm, yeah I guess that's probably not the most elegant flow for a non-cli app. You'd have to effectively rewrite the `oauth_auth` function to work around that one line.

Just off the top of my head I'm thinking we could probably refactor the `oauth_auth` function to take a callback that's responsible for dealing with fetching the access token.

Something along the lines of:

```python
def terminal_oath_callback(authorization_url):
    """default oath callback used for terminal applications"""
    print('Please go here and authorize,', authorization_url)

    # Get the authorization verifier code from the callback url
    response = six.moves.input('Paste the Code returned here: ')
    # Fetch, assign, and return the access token
    oauth.fetch_token(token_url, client_secret=CLIENT_SECRET, code=response)
    return oauth.token['access_token']


def oauth_auth(username, client_id=None, client_secret=None, store=False, oauth_cb=terminal_oath_callback):
    # ...cut for brevity...
    authorization_url, _ = oauth.authorization_url(authorization_base_url,
                                                   username=username)
    OAUTH_TOKEN = oauth_cb(authorization_url)

    if store:
        _store(CLIENT_ID=CLIENT_ID, CLIENT_SECRET=CLIENT_SECRET,
               OAUTH_TOKEN=OAUTH_TOKEN)
    return OAUTH_TOKEN
```

This way you, or anyone that isn't writing a CLI, could write a small callback function (maybe even add one to PyTrakt?) to get your token in a manner that makes the most sense for your service by passing a callback to `oauth_auth` or `init` that will handle the token exchange.

Does that sound like it would address your issue?

**Comment by Forcide** [comment]
You could also decide to let the callback function only handle the providing of the OAUTH pin, if that is desired.
Something like this:

```
def terminal_oauth_pin(authorization_url):
    """default oauth callback used for terminal applications"""
    print('Please go here and authorize,', authorization_url)

    # Get the authorization verifier code from the callback url
    response = six.moves.input('Paste the Code returned here: ')
    return response

def oauth_auth(username, client_id=None, client_secret=None, store=False, oauth_cb=terminal_oauth_pin):
    # ...............................
    authorization_url, _ = oauth.authorization_url(authorization_base_url,
                                                   username=username)
    oauth_pin = oauth_cb(authorization_url)
    
    # Fetch, assign, and return the access token
    oauth.fetch_token(token_url, client_secret=CLIENT_SECRET, code=oauth_pin)
    OAUTH_TOKEN = oauth.token['access_token']

    if store:
        _store(CLIENT_ID=CLIENT_ID, CLIENT_SECRET=CLIENT_SECRET,
               OAUTH_TOKEN=OAUTH_TOKEN)
    return OAUTH_TOKEN
```

**Comment by Forcide** [comment]
I made another example, which works in my use case, but I don't know if it is desirable for others because I actually don't use the `authorization_url`.
I added `oauth_pin` to `oauth_auth`. If it is left empty nothing changes, but if a pin is provided it will skip the terminal step.

```
def oauth_auth(username, client_id=None, client_secret=None, store=False,
               oauth_pin=None):
    """Generate an access_token to allow your application to authenticate via
    OAuth

    :param username: Your trakt.tv username
    :param client_id: Your Trakt OAuth Application's Client ID
    :param client_secret: Your Trakt OAuth Application's Client Secret
    :param store: Boolean flag used to determine if your trakt api auth data
        should be stored locally on the system. Default is :const:`False` for
        the security conscious
    :return: Your OAuth access token
    """
    global CLIENT_ID, CLIENT_SECRET, OAUTH_TOKEN
    if client_id is None and client_secret is None:
        client_id, client_secret = _get_client_info()
    CLIENT_ID, CLIENT_SECRET = client_id, client_secret
    HEADERS['trakt-api-key'] = CLIENT_ID

    token_url = urljoin(BASE_URL, '/oauth/token')

    # OAuth endpoints given in the API documentation
    oauth = OAuth2Session(CLIENT_ID, redirect_uri=REDIRECT_URI, state=None)

    if oauth_pin is None:
        # Redirect user to Trakt for authorization
        authorization_base_url = urljoin(BASE_URL, '/oauth/authorize')
        authorization_url, _ = oauth.authorization_url(authorization_base_url,
                                                       username=username)
        print('Please go here and authorize,', authorization_url)

        # Get the authorization verifier code from the callback url
        response = six.moves.input('Paste the Code returned here: ')
        oauth_pin = response

    # Fetch, assign, and return the access token
    oauth.fetch_token(token_url, client_secret=CLIENT_SECRET, code=oauth_pin)
    OAUTH_TOKEN = oauth.token['access_token']

    if store:
        _store(CLIENT_ID=CLIENT_ID, CLIENT_SECRET=CLIENT_SECRET,
               OAUTH_TOKEN=OAUTH_TOKEN)
    return OAUTH_TOKEN
```

**Comment by Forcide** [comment]
Do you want the callback function to handle the token exchange or only for getting the OAuth pin?

**Comment by moogar0880** [comment]
I'm going to close this issue now that [2.9.0](https://pypi.org/project/trakt/) has been published to PyPi. Feel free to re-open if the new callback doesn't solve the original issue.
