### ISSUE TITLE
TvShow.seasons returns same season for each object

### ISSUE THREAD

**Issue by iantrich** [moogar0880/PyTrakt#98]
![image](https://user-images.githubusercontent.com/1287159/51883299-e8fc2680-2347-11e9-8129-427442f23070.png)

The bug is not obvious to me, but calling the same query, manually, gives both individual seasons:

![image](https://user-images.githubusercontent.com/1287159/51883880-89ebe100-234a-11e9-9cfc-3a018103e142.png)

Should this [line](https://github.com/moogar0880/PyTrakt/blob/master/trakt/tv.py#L252) be explicit about the season number? My Python is limited and I would actually think this should be fine, as "number" looks to be returned first and would therefore be the 2nd parameter passed to init of the TvSeason as expected...I'm not sure

**Comment by iantrich** [comment]
I'll try to play around with the code to see if I can better pin-point where the issue is

**Comment by iantrich** [comment]
![image](https://user-images.githubusercontent.com/1287159/51884465-fb2c9380-234c-11e9-86f8-3b72dfca93ab.png)

Number is getting passed in, the season value is not being set it looks like.

So should that line just be 
```python
self._seasons.append(TVSeason(self.title, season.number, **season))
```

**Comment by StoneMonarch** [comment]
@iantrich 

your fix doesnt work. i get this error when i add your fix
`self._seasons.append(TVSeason(self.title, season.number, **season))
AttributeError: 'dict' object has no attribute 'number'`

**Comment by iantrich** [comment]
@StoneMonarch yeah, that's why I didn't finish the PR. Haven't had a chance to look into it further

**Comment by StoneMonarch** [comment]
Fixed, see PR #100

**Comment by StoneMonarch** [comment]
@iantrich please mark as closed

**Comment by moogar0880** [comment]
Closing this issue since, as @StoneMonarch said, this was closed in #100. 

If you run into any other issues feel free to open a new issue.

**Comment by iantrich** [comment]
Works here. I planned to use this for an "Up Next" sensor in Home Assistant, which I do have working but unfortunately it is just too slow to get all the episodes for the most recently watched and find the next. Ends up taking ~5 minutes :( There's not an "up next" api call that I'm missing, is there?

**Comment by moogar0880** [comment]
Yeah, the trakt api isn't super quick. 

Have you tried lowering the number of days when you get the calendar? By default it gets the next weeks worth of episodes, you could try setting `days=2`. The response may come back faster.

**Comment by iantrich** [comment]
I have a calendar sensor working perfectly, but the way I'm going "Up Next" is by getting `watched_shows` for the users, which has the most recently watched shows. I then iterate through those and do a `TvShow.search` on each show to get all episodes, and use that to get the next show after the most recently watched. The search is where the bottleneck is.

**Comment by dhjw** [comment]
Note the apparent correct way to obtain Up Next according to https://trakt.docs.apiary.io/#reference/users/watchlist/get-watchlist is "Use a combination of the [/sync/watched](https://trakt.docs.apiary.io/reference/sync/get-watched) and [/shows/:id/progress](https://trakt.docs.apiary.io/reference/shows/watched-progress) methods to get what the user is actively watching." This functionality is available in the fork at https://github.com/glensc/python-pytrakt and is called per https://pytrakt.readthedocs.io/en/latest/users.html#examples like `User(user).watched_shows[0].watched_progress()`

**Comment by dhjw** [comment]
The apparent correct way to obtain Up Next according to a note [here](https://trakt.docs.apiary.io/#reference/users/watchlist/get-watchlist) is to "Use a combination of the [/sync/watched](https://trakt.docs.apiary.io/reference/sync/get-watched) and [/shows/:id/progress](https://trakt.docs.apiary.io/reference/shows/watched-progress) methods to get what the user is actively watching." The progress endpoints are accessible with [this fork](https://github.com/glensc/python-pytrakt) (`pip uninstall trakt; git clone https://github.com/glensc/python-pytrakt; cd python-pytrakt; pip install .` then import trakt as usual) and is called similar to the example in [these docs](https://pytrakt.readthedocs.io/en/latest/users.html#examples) with the additional [function](https://github.com/glensc/python-pytrakt/blob/9a4f9f2e5a9903ef6fc727c049f7eca8f3fadd78/trakt/tv.py#L364), like `User(user).watched_shows[0].watched_progress()`
